spring.application.name=chapter2
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/ABC/employeeDB
spring.datasource.username=aabir23
spring.datasource.password=aabir23
spring.jpa.hibernate.ddl-auto=create
